### ISSUE TITLE
Eje Y de gráficas esta cortado

### ISSUE THREAD

**Issue by federicosq85** [coronamex/datos#2]
Hola Sur! Felicidades por la inciativa, esta muy buenas las gráficas. Las gráficas parecen estar cortadas hacia su extremo izquierdo, no se aprecian los ejes "y" de las mismas. Podŕia ser algo de las gráficas o que todo esta desfasado hacia la derecha? 
Gracias y saludos

**Comment by surh** [comment]
En que navegador y sistema operativo?

**Comment by federicosq85** [comment]
Firefox 74, Ubuntu 18.04.2

**Comment by surh** [comment]
Debe haber mejorado con el último commit (https://github.com/coronamex/coronamex.github.io/commit/84c7874254f19c1bcd437bd11d54c8c3342cc3ba). 

Añadí tamaños de imágenes y algo de margen para incrementar la responsividad del sitio. No es perfecto pero en mis pruebas se ve bien:

![image](https://user-images.githubusercontent.com/10564069/78100221-0805a680-7399-11ea-8e15-df88eab21413.png)

Estoy cerrando este issue por el momento, pero puede volverse a abrir si sigue habiendo problemas.

A mediano plazo lo ideal sería implementar algo como [esto](https://dev.to/stereobooster/responsive-images-for-hugo-dn9)

Sur
